version: '3.1'
services:
    money-management-app:
        build: .
        env_file: 
            - ./.env
        volumes: 
            - ./:/opt/app/src
        ports:
            - '${PORT}:${PORT}'
        restart: unless-stopped
        command: nodemon index.js